using System;

public enum DMSMapConfMember
{
	DMS_MAPCONF_ATTR,
	DMS_MAPCONF_VERSION,
	DMS_MAPCONF_BGNO,
	DMS_MAPCONF_LIGHTCOUNT,
	DMS_MAPCONF_LIGHTUSE,
	DMS_MAPCONF_CHARCOUNT,
	DMS_MAPCONF_CHARUSE,
	DMS_MAPCONF_EVTCOUNT,
	DMS_MAPCONF_EVTUSE,
	DMS_MAPCONF_COUNT
}
