using System;

public enum CAMERA_NO
{
    CAMERA_NO_PLUNGE,
    CAMERA_NO_DEFAULT,
    CAMERA_NO_WIN,
    CAMERA_NO_PC_0,
    CAMERA_NO_PC_1,
    CAMERA_NO_MON_0,
    CAMERA_NO_MON_1,
    CAMERA_NO_MON_2
}
