using System;

public enum QuadMistSoundID
{
	MINI_SE_CURSOL = 1,
	MINI_SE_WARNING,
	MINI_SE_CANCEL,
	MINI_SE_CARD_GET,
	MINI_SE_CARD_MOVE,
	MINI_SE_COIN,
	MINI_SE_WALL,
	MINI_SE_PERFECT,
	MINI_SE_FLASH,
	MINI_SE_COMB,
	MINI_SE_BOMB,
	MINI_SE_WINDOW,
	MINI_SE_WIN,
	MINI_SE_LOSE,
	MINI_SE_DRAW
}
