using System;

public enum FF9PLAY_CHAR
{
	FF9PLAY_CHAR_ZIDANE,
	FF9PLAY_CHAR_VIVI,
	FF9PLAY_CHAR_GARNET,
	FF9PLAY_CHAR_STEINER,
	FF9PLAY_CHAR_FREIJA,
	FF9PLAY_CHAR_KUINA,
	FF9PLAY_CHAR_EIKO,
	FF9PLAY_CHAR_SALAMANDER,
	FF9PLAY_CHAR_CINNA,
	FF9PLAY_CHAR_MARCUS,
	FF9PLAY_CHAR_BLANK,
	FF9PLAY_CHAR_BEATRIX,
	FF9PLAY_CHAR_MAX
}
