using System;

internal enum FF9FieldFMVServiceStatus
{
	FF9FIELD_FMVSERVICE_IDLE,
	FF9FIELD_FMVSERVICE_INIT,
	FF9FIELD_FMVSERVICE_OVERLAY,
	FF9FIELD_FMVSERVICE_OVERLAYINIT,
	FF9FIELD_FMVSERVICE_SEEK,
	FF9FIELD_FMVSERVICE_READY,
	FF9FIELD_FMVSERVICE_SERVICE,
	FF9FIELD_FMVSERVICE_PURGE,
	FF9FIELD_FMVSERVICE_COMPLETE,
	FF9FIELD_FMVSERVICE_BADDISC = 17
}
