name: Build Memoria Patcher

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Decrypt and extract dependencies
      env:
        ARCHIVE_PASSWORD: ${{ secrets.DEPENDENCIES_PASSWORD }}
      shell: pwsh
      run: |
        7z x .\References\Dependencies.7z -p"$($env:ARCHIVE_PASSWORD)" -oReferences -y

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v2

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.nuget/packages
        key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.config', '**/*.csproj') }}
        restore-keys: |
          nuget-${{ runner.os }}-

    - name: NuGet restore
      run: nuget restore Memoria.sln

    - name: Build Memoria.MSBuild.csproj (Release)
      run: msbuild Memoria.MSBuild/Memoria.MSBuild.csproj /t:Build /p:Configuration=Release

    - name: Build main solution (Release)
      run: msbuild Memoria.sln /t:Build /p:Configuration=Release

    - name: Publish Memoria.Patcher (Win-x64)
      run: msbuild Memoria.Patcher/Memoria.Patcher.csproj "/t:Clean;Publish" /p:PublishProfile=Win-x64

    - name: Publish Memoria.Patcher (Linux-x64)
      run: msbuild Memoria.Patcher/Memoria.Patcher.csproj "/t:Clean;Publish" /p:PublishProfile=Linux-x64

    - name: Publish Memoria.Patcher (Osx-x64)
      run: msbuild Memoria.Patcher/Memoria.Patcher.csproj "/t:Clean;Publish" /p:PublishProfile=Osx-x64

    - name: Upload Win-x64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: Memoria-Patcher-Win-x64
        path: Output/win-x64/Memoria.Patcher.exe

    - name: Upload Linux-x64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: Memoria-Patcher-Linux-x64
        path: Output/linux-x64/Memoria.Patcher

    - name: Upload Osx-x64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: Memoria-Patcher-Osx-x64
        path: Output/osx-x64/Memoria.Patcher
    - name: Rename output files
      run: |
        mv "Output/linux-x64/Memoria.Patcher" "Output/linux-x64/Memoria.Patcher-linux-x64"
        mv "Output/osx-x64/Memoria.Patcher" "Output/osx-x64/Memoria.Patcher-osx-x64"
    - name: Release Memoria.Patcher (Canary)
      uses: softprops/action-gh-release@v2
      with:
        name: Memoria (Canary)
        files: |
          Output/win-x64/Memoria.Patcher.exe
          Output/linux-x64/Memoria.Patcher-linux-x64
          Output/osx-x64/Memoria.Patcher-osx-x64
        generate_release_notes: true
        draft: false
        prerelease: true
        tag_name: canary
        overwrite_files: true
        body: |
          This is a canary build. Please be aware it may be prone to crashing and is NOT tested by anyone. Use this build AT YOUR OWN RISK!
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Move canary tag to this commit
      uses: richardsimko/update-tag@v1
      with:
        tag_name: canary
