namespace FF9
{
	internal enum battle_phase_menu_off
	{
		BTL_MENU_OFF_SEQ_VICTORY,
		BTL_MENU_OFF_SEQ_DEFEAT,
		BTL_MENU_OFF_SEQ_EVENT,
		BTL_MENU_OFF_SEQ_ESCAPE,
		BTL_MENU_OFF_SEQ_VICTORY_WITH_ENEMY
	}
}
