using System;

namespace FF9
{
    internal enum chara_script_id_tags
    {
        ID_ADD_CHARACTER = 32,
        ID_DELETE_CHARACTER,
        ID_KILL_COMMAND2,
        ID_MAX_HP,
        ID_CUR_HP,
        ID_MAX_MP,
        ID_CUR_MP,
        ID_MAX_AT,
        ID_CUR_AT,
        ID_LEVEL,
        ID_STAT_INVALID_HIGH,
        ID_STAT_INVALID_LOW,
        ID_STAT_PERMANENT_HIGH,
        ID_STAT_PERMANENT_LOW,
        ID_STAT_CURRENT_HIGH,
        ID_STAT_CURRENT_LOW,
        ID_DEFEND_ATTR_INVALID,
        ID_DEFEND_ATTR_ABSORB,
        ID_DEFEND_ATTR_HALF,
        ID_DEFEND_ATTR_WEAK,
        ID_INFO_TARGET,
        ID_INFO_DISAPPEAR,
        ID_INFO_SHADOW,
        ID_SET_SCALE,
        ID_RESET_SCALE,
        ID_DMS_GEO_ID,
        ID_MESH_CURRENT,
        ID_MESH_CURRENT_HIDE,
        ID_MESH_CURRENT_SHOW,
        ID_TEX_ANIM_PLAY,
        ID_TEX_ANIM_STOP,
        ID_TEX_ANIM_PLAY_ONCE,
        ID_PLAYER_ROW,
        ID_PLAYER_COLUMN,
        ID_PLAYER_SERIAL,
        ID_PLAYER_CATEGORY,
        ID_ENEMY_CATEGORY,
        ID_ENEMY_IDLE,
        ID_ENEMY_SLOT,
        ID_SET_ENEMY_BONUS,
        ID_ELEM_STR,
        ID_ELEM_MGC,
        ID_PARAM_P_DEF,
        ID_PARAM_P_EV,
        ID_PARAM_M_DEF,
        ID_PARAM_M_EV,
        ID_SET_CMD_SUMMON_RAY
    }
}
