using System;

namespace FF9
{
	internal enum command_type
	{
		FF9COMMAND_TYPE_NORMAL,
		FF9COMMAND_TYPE_ABILITY,
		FF9COMMAND_TYPE_ITEM,
		FF9COMMAND_TYPE_THROW,
		FF9COMMAND_TYPE_SLIDE,
		FF9COMMAND_TYPE_MAX
	}
}
