using System;

namespace FF9
{
	public enum stat_table
	{
		STAT_TBL_STONE,
		STAT_TBL_POISON2,
		STAT_TBL_VIRUS,
		STAT_TBL_SILENCE,
		STAT_TBL_DARK,
		STAT_TBL_TROUBLE,
		STAT_TBL_ZOMBIE,
		STAT_TBL_SAFETY,
		STAT_TBL_DISABLE,
		STAT_TBL_DYING,
		STAT_TBL_CONFU,
		STAT_TBL_BERSERK,
		STAT_TBL_STOP,
		STAT_TBL_RERAISE,
		STAT_TBL_TRANSFORM,
		STAT_TBL_DEFENCE,
		STAT_TBL_POISON,
		STAT_TBL_SLEEP,
		STAT_TBL_REGENE,
		STAT_TBL_HASTE,
		STAT_TBL_SLOW,
		STAT_TBL_LEVITATE,
		STAT_TBL_SHELL,
		STAT_TBL_PROTES,
		STAT_TBL_HEAT,
		STAT_TBL_FREEZE,
		STAT_TBL_BANISH,
		STAT_TBL_CONDEMN,
		STAT_TBL_MINI,
		STAT_TBL_REFLEC,
		STAT_TBL_JUMP,
		STAT_TBL_STONING
	}
}
