using System;

namespace FF9
{
	internal enum sys_set_script_id_tags
	{
		ID_START_EVENT_BATTLE = 32,
		ID_START_BATTLE_CLOSE,
		ID_START_GAMEOVER,
		ID_RESTART_BATTLE,
		ID_SET_CAMERA,
		ID_BATTLE_MAP_JUMP,
		ID_ADD_PARTY_GIL,
		ID_INCREMENT_DRAGON,
		ID_BATTLE_SONG_FADEOUT
	}
}
