namespace FF9
{
	internal enum sys_get_script_id_tags
	{
		ID_START_TYPE = 32,
		ID_TOTAL_GIL,
		ID_BATTLE_PHASE,
		ID_BATTLE_SEQUENCE,
		ID_CUR_CMD_EXEC_ID,
		ID_CUR_CMD_TAR_ID,
		ID_CUR_CMD_WEAPON_ATTR,
		ID_CUR_CMD_MAGIC_ATTR,
		ID_BATTLE_LOAD_STATUS,
		ID_BONUS_EXP,
		ID_CHECK_SYS_PHOENIX_ENTRY
	}
}
